#!/bin/bash

#Customize this stuff
IF="Master"
SECS="1"
COLOR_ICON="#6e9bcf"
FONT="fixed"
BG="grey"
FG="black"
XPOS="750"
YPOS="525"
WIDTH="400"
HEIGHT="30"
#Probably do not customize
PIPE="/tmp/dvolpipe"
ICON=~/.xbm/spkr_02.xbm
err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit
}
#Argument Parsing
case "$1" in
  'up')
    [ -z "$2" ] && err "No argument specified for increase."
    AMIXARG="$1 ${2}"
    ;;
  'down'|'set')
    [ -z "$2" ] && err "No argument specified for decrease."
    AMIXARG="$1 ${2}"
    ;;
  'toggle')
    AMIXARG="toggle"
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(volume_control.py $AMIXARG)"
MUTE="$(volume_control.py status)"
if [ "$MUTE" = "muted" ]; then
  VOL="0"
else
  VOL="$(volume_control.py read)"
fi

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
if [ ! -e "$PIPE" ]; then
  mkfifo "$PIPE"
  (dzen2 -l 1 -x "$XPOS" -y "$YPOS" -w "$WIDTH" -h "$HEIGHT" -fn "$FONT" -bg "#000000" -fg "#bebebe" -e 'onstart=uncollapse' < "$PIPE"
   rm -f "$PIPE") &
fi

#Feed the pipe!
(echo "^fg(#696969)^i($ICON) Volume" ; echo "$VOL" | gdbar -max 150 -bg "#000000" -fg "#a9a9a9" -w 400 ; sleep "$SECS") > "$PIPE"
